### PR TITLE
Code generation FROM tests

### PR DESCRIPTION
**Pull request by deanwampler**
It **is** possible to generate code from unit tests! Using _property-based_ tests written in [hypothesis](https://hypothesis.readthedocs.io/en/latest/), generating the `Rational` didn't always work successfully, but some runs produced very good implementations. Ironically, if you look at the output (which I didn't clear for this WiP), you'll see that the Ollama run produced a much better implementation (but also spit out the tests again) compared to the Replicate run (which at least didn't regurgitate the tests).

I captured the best output in `.../rational/rational-good-example.py`.

Before this PR can be marked done, It probably needs to be changed to just use Replicate for the model.

### CODE REVIEW

**Comment by deanwampler** [comment]
I finally completed this recipe, converting it to use Replicate through langchain, like the rest. So, it's ready for review.

**Review by rawkintrevo — APPROVED** [review]
The testing looks good, but really I'm handing that aspect off to @bjhargrave who is refactoring it all to make it cleaner, so going forward you'll want to add things that way.

**Comment by rawkintrevo** [comment]
NOTE to anyone doing driveby merges- my approval is related to the testing facet only, and should not imply that this code is good to merge (the failing test implies that it is not)

**Comment by deanwampler** [comment]
Yeah, it appears that `Auto_Documentation.ipynb` is what's failing.

**Comment by bjhargrave** [comment]
> Yeah, it appears that `Auto_Documentation.ipynb` is what's failing.

Yeah. I made a fix to that in #154. The failure was caused by my fix in https://github.com/ibm-granite-community/utils/pull/25/commits/c986233856b83c8a167e5c43e06190dd6e53b495 which moved the source files into a `src` folder. So the notebook was looking for a folder which no longer existed.

Once the fix in #154 is merged, you can rebase. You will also need to remove vanilla_workflow from this PR since it has been removed in HEAD. You only need to list the notebooks in the notebooks txt file now.

**Comment by deanwampler** [comment]
Will do. Thanks.

**Comment by deanwampler** [comment]
The PR deltas got a bit messy, so I created a new PR #155

**Pull request closed without merging**
