### PR TITLE
Update Getting Started to use ibm-granite model (8b-128k) on Replicate

### PR DESCRIPTION
**Pull request by fayvor**
Tidy up the Getting Started recipe:

- Remove empty/broken sections (Local models, Langchain).
- Update the model to use `ibm-granite/granite-8b-code-instruct-128k` on replicate.
- Update the prompt section to use `model` instead of `deployment`.
- Test (it works).

### CODE REVIEW

**Comment by adampingel** [comment]
@fayvor I think @deanwampler just added the local/ollama stuff in his PR.  Can we pull those changes in here?

**Comment by deanwampler** [comment]
The only useful change I suggested in the Getting Started notebook was to replace the two empty cells with a markdown cell that says this notebook looks at remote hosting. See the Continue... notebook for info about local hosting with Ollama. No problem if you don't want to use it.

**Comment by deanwampler** [comment]
(I also cleared all the cell output, but that's not so important either...)

**Comment by deanwampler** [comment]
If you approval, otherwise, Adam, I recommend you merge this and I'll rebase my PR on it later this evening. I don't want this to block us, since this PR affects one notebook and mine affects two.

**Comment by fayvor** [comment]
@deanwampler I'm ok either way; let me know if you want me to merge your changes into this one.

**Comment by deanwampler** [comment]
Nah, go ahead and merge your PR when ready and I'll rebase. Keep it simple...

**Pull request merged**
