### PR TITLE
Code Assistant in VSCode Recipe Fixes

### PR DESCRIPTION
**Pull request by fayvor**
Per #51:
- Install 8b and 3b on Ollama as well as 20b
- Fix the title of the Replicate connection (8b)

### CODE REVIEW

**Review by deanwampler — APPROVED** [review]
👍

**Comment by deanwampler** [comment]
@fayvor do you want me to merge this?

**Comment by fayvor** [comment]
> @fayvor do you want me to merge this?

@deanwampler yes, please. I'm blocked from merging.

**Comment by deanwampler** [comment]
Done! Thanks for letting me know that one of us needs to do the merges for you.

**Pull request merged**
