### PR TITLE
HAP recipe

### PR DESCRIPTION
**Pull request by deanwampler**
I cleaned up and got it working with box-located download of the model.

Note that on MacOS, you should just use the CPU. It appears that Apple Silicon acceleration doesn't work.

### CODE REVIEW

**Comment by rawkintrevo** [comment]
Working with Dean. This works in Colab, and CPU is A.O.K. for all usecases. Also, clear the outputs and this LGTM my .02

**Review by rawkintrevo — APPROVED** [review]

**Comment by deanwampler** [comment]
I'll merge this. Apparently they just got permission to OS the model and put it on HF. After that's done, we can move the location...

**Comment by deanwampler** [comment]
Ooops. I forgot to clean the output. Let's do that when we move to the final model location.

**Comment by fayvor** [comment]
Scanning this I have a couple of comments:

1. Change `prompt_list_splited` to `prompt_list_splitted` (or just `prompt_list_split`).
2. Did we write the hap_scorer from scratch? Is there a library where that should go?

**Comment by deanwampler** [comment]
I'll do a new PR with that variable rename. Agree that the current one is bad... 

The `hap_scorer` probably should go into a library, at least once have more recipes.

**Pull request merged**
